// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolMVCef.Data;

namespace SchoolMVCef.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210603032334_InsertIntoStudentsAndTeachers")]
    partial class InsertIntoStudentsAndTeachers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SchoolMVCef.Models.StudentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "RioDan S"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Muhhanad Sami"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rami Gh"
                        });
                });

            modelBuilder.Entity("SchoolMVCef.Models.TeacherModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ali S"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sami W"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Y Soul"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
