// <auto-generated />
using CodeFirstApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirstApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210601135434_InsertCustomers")]
    partial class InsertCustomers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CodeFirstApp.Models.BranchModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("CodeFirstApp.Models.CustomerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmadAli@gmail.com",
                            FirstName = "Ahmad",
                            LastName = "Ali"
                        },
                        new
                        {
                            Id = 2,
                            Email = "HanaZaid@gmail.com",
                            FirstName = "Hanan",
                            LastName = "Zaid"
                        },
                        new
                        {
                            Id = 3,
                            Email = "RanaQa@gmail.com",
                            FirstName = "Ranan",
                            LastName = "Qassim"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Rana21@gmail.com",
                            FirstName = "Jana",
                            LastName = "Muath"
                        });
                });

            modelBuilder.Entity("CodeFirstApp.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Black",
                            Name = "iPhone 12",
                            Price = 3222.92f
                        },
                        new
                        {
                            Id = 2,
                            Color = "Red",
                            Name = "iPhone 11",
                            Price = 2499f
                        },
                        new
                        {
                            Id = 3,
                            Color = "Grey",
                            Name = "iPhone 11",
                            Price = 2499f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
