// <auto-generated />
using CodeFirstApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirstApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210602131204_relationsbetweenCustomertableAndProfileTable")]
    partial class relationsbetweenCustomertableAndProfileTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CodeFirstApp.Models.BranchModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("id");

                    b.ToTable("Branchs");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Address = "Riyadh",
                            Area = "Alnakuli",
                            Name = "Branch01"
                        },
                        new
                        {
                            id = 2,
                            Address = "Riyadh",
                            Area = "Alnakuli",
                            Name = "Branch02"
                        },
                        new
                        {
                            id = 3,
                            Address = "Riyadh",
                            Area = "Alnakuli",
                            Name = "Branch03"
                        },
                        new
                        {
                            id = 4,
                            Address = "Riyadh",
                            Area = "Alnakuli",
                            Name = "Branch04"
                        },
                        new
                        {
                            id = 5,
                            Address = "Riyadh",
                            Area = "Alnakuli",
                            Name = "Branch05"
                        });
                });

            modelBuilder.Entity("CodeFirstApp.Models.CustomerModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Email = "AbdulrahmanJ@gmail.com",
                            FirstName = "Abdulrahman",
                            LastName = "Aljfar"
                        },
                        new
                        {
                            id = 2,
                            Email = "AbdulrahmanJ@gmail.com",
                            FirstName = "Abdulrahman",
                            LastName = "Aljfar"
                        },
                        new
                        {
                            id = 3,
                            Email = "AbdulrahmanJ@gmail.com",
                            FirstName = "Abdulrahman",
                            LastName = "Aljfar"
                        },
                        new
                        {
                            id = 4,
                            Email = "AbdulrahmanJ@gmail.com",
                            FirstName = "Abdulrahman",
                            LastName = "Aljfar"
                        },
                        new
                        {
                            id = 5,
                            Email = "AbdulrahmanJ@gmail.com",
                            FirstName = "Abdulrahman",
                            LastName = "Aljfar"
                        });
                });

            modelBuilder.Entity("CodeFirstApp.Models.ProductModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CodeFirstApp.Models.ProfileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ative")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("CodeFirstApp.Models.ProfileModel", b =>
                {
                    b.HasOne("CodeFirstApp.Models.CustomerModel", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
