// <auto-generated />
using CodeFirstApp1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirstApp1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210602114304_insertIntoCustomres")]
    partial class insertIntoCustomres
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CodeFirstApp1.Models.BranchModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Riyadh",
                            Area = 1,
                            Name = "Br1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Makkah",
                            Area = 12,
                            Name = "Br2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Jeddah",
                            Area = 3,
                            Name = "Br3"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Dammam",
                            Area = 8,
                            Name = "Br4"
                        });
                });

            modelBuilder.Entity("CodeFirstApp1.Models.CustomerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sara@gmail",
                            Name = "sara"
                        },
                        new
                        {
                            Id = 2,
                            Email = "amal@gmail",
                            Name = "amal"
                        },
                        new
                        {
                            Id = 3,
                            Email = "battal@gmail",
                            Name = "battal"
                        },
                        new
                        {
                            Id = 4,
                            Email = "fares@gmail",
                            Name = "fares"
                        });
                });

            modelBuilder.Entity("CodeFirstApp1.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
